In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/Users/jayanto/Desktop/train.txt",sep=";",header=None,names=["text","emotion"])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum().sum()

np.int64(0)

In [5]:
unique_emotion=df["emotion"].unique()
emotion_num={}
i=0
for emo in unique_emotion:
    emotion_num[emo]=i
    i+=1

df["emotion"]=df["emotion"].map(emotion_num)

In [6]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
df["text"]=df["text"].apply(lambda x:x.lower())

In [8]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans(" "," ",string.punctuation))

In [9]:
df["text"]=df["text"].apply(remove_punc)

In [10]:
def remove_num(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [12]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /Users/jayanto/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/jayanto/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/jayanto/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
stop_words=set(stopwords.words("english"))

In [14]:
def remove(txt):
    words = word_tokenize(txt)
    clean = []
    for i in words:
        if i.lower() not in stop_words:
            clean.append(i)
    return " ".join(clean)

df["text"] = df["text"].apply(remove)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["emotion"], test_size=0.20, random_state=42
)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [40]:
bow_vectorizer = CountVectorizer()

In [41]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [42]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [43]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [44]:
print(X_train.shape, X_train_bow.shape, y_train.shape)
print(X_test.shape, X_test_bow.shape, y_test.shape)

(12800,) (12800, 13359) (12800,)
(3200,) (3200, 13359) (3200,)

In [45]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

In [46]:
tfidf_vectorizer=TfidfVectorizer()

In [48]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [49]:
nb2_model=MultinomialNB()
nb2_model.fit(X_train_bow, y_train)

MultinomialNB()

In [57]:
y_pre = nb2_model.predict(X_train)

ValueError: could not convert string to float: 'refers course though cant help feeling somehow ironically retrospect loudons son kate mcgarrigle rather talented rufus wainwright'

In [55]:
print(accuracy_score(y_test, y_pre))

ValueError: Found input variables with inconsistent numbers of samples: [3200, 12800]